#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check ESLint Standards
npm run lint ||
(
  echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
          ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

# Check tsconfig standards
npm run type-check ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# Check format code
npm run format && git add -A .